server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: "${EUREKA_ZONE:http://localhost:8761/eureka/}"

spring:
  application:
    name: exchange-rate
  sleuth:
    sampler:
      probability: 1
  zipkin:
    baseUrl: ${ZIPKIN_BASE_URL:http://localhost:9411}

okta:
  oauth2:
    issuer: https://feketegabor.okta.com/oauth2/default
    audience: api://default

logging:
  level:
    org.springframework.security: DEBUG
